[[redirects]]
    from = "/app1"
    to = "https://app1-react-single-spa.netlify.com"
    status = 200
    force = true
    headers = {Access-Control-Allow-Origin = "*", "Access-Control-Allow-Methods" = "GET, POST, PUT, DELETE, PATCH, OPTIONS", "Access-Control-Allow-Headers" = "X-Requested-With, content-type, Authorization"}

[[headers]]
    for = "/app1/*"
    [headers.values]
        Access-Control-Allow-Origin = "*"